name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deployment-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY_URL: ${{ secrets.REGISTRY_URL_PROD }}
  REGISTRY_USR: ${{ secrets.REGISTRY_USERNAME_PROD }}
  REGISTRY_PWD: ${{ secrets.REGISTRY_PASSWORD_PROD }}
  TAG: v${{ github.run_number }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3

    # Login to Harbor
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_URL }}
        username: ${{ env.REGISTRY_USR }}
        password: ${{ env.REGISTRY_PWD }}

    # 🔧 Build & push backend (also used by huey)
    - name: Build & Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        tags: |
          ${{ env.REGISTRY_URL }}/dats-harici/ciso-backend:${{ env.TAG }}
        push: true

    # 🔧 Build & push frontend
    - name: Build & Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        tags: |
          ${{ env.REGISTRY_URL }}/dats-harici/ciso-frontend:${{ env.TAG }}
        push: true

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCE_SA_KEY }}'

    - name: Deploy to GCE via SSH
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name: ${{ secrets.GCE_VM }}
        zone: ${{ secrets.GCE_ZONE }}
        ssh_private_key: ${{ secrets.GCE_SSH_KEY }}
        command: |
          sh -c '
            docker login ${{ env.REGISTRY_URL }} -u ${{ env.REGISTRY_USR }} -p ${{ env.REGISTRY_PWD }}

            echo "services:" > /opt/ciso/docker-compose.override.yml
            echo "  backend:" >> /opt/ciso/docker-compose.override.yml
            echo "    image: ${{ env.REGISTRY_URL }}/dats-harici/ciso-backend:${{ env.TAG }}" >> /opt/ciso/docker-compose.override.yml
            echo "  frontend:" >> /opt/ciso/docker-compose.override.yml
            echo "    image: ${{ env.REGISTRY_URL }}/dats-harici/ciso-frontend:${{ env.TAG }}" >> /opt/ciso/docker-compose.override.yml
            echo "  huey:" >> /opt/ciso/docker-compose.override.yml
            echo "    image: ${{ env.REGISTRY_URL }}/dats-harici/ciso-backend:${{ env.TAG }}" >> /opt/ciso/docker-compose.override.yml

            docker compose -f /opt/ciso/docker-compose.yml -f /opt/ciso/docker-compose.override.yml up -d
          '